/*
 * This source file was generated by the Gradle 'init' task
 */
package taller5;

public class App {
    
    public static void main(String[] args) {
        
        try {
            
        } 
        
        catch (Exception e) {
            // TODO: handle exception
        }
    }


    /*
    
        1.	Desarrolle un algoritmo e impleméntelo en Java que: le pida al usuario un número entero positivo 
        entre 1000 y 9999. En un ciclo genere números de manera aleatoria y cuente los intentos que hizo antes 
        de hallar el número exactamente.
        
    
    */ 


    public static String adivinarNumero() {
    try {
        final short LIMITE_INFERIOR = 1000;
        final short LIMITE_SUPERIOR = 10000;
        final byte UNO = 1;
        Scanner entrada = new Scanner(System.in);

        short numeroSeleccionado;
        do {
            System.out.println("Ingrese un número entre 1000 y 9999: ");
            numeroSeleccionado = entrada.nextShort();
            if (numeroSeleccionado < LIMITE_INFERIOR || numeroSeleccionado >= LIMITE_SUPERIOR) {
                System.out.println("El número no está dentro del rango especificado. Inténtelo de nuevo.");
            }
        } while (numeroSeleccionado < LIMITE_INFERIOR || numeroSeleccionado >= LIMITE_SUPERIOR);

        short numeroAleatorio;
        short conteoIntentos = 0;
        do {
            numeroAleatorio = (short) (Math.random() * (LIMITE_SUPERIOR - LIMITE_INFERIOR) + LIMITE_INFERIOR);
            conteoIntentos++;
        } while (numeroAleatorio != numeroSeleccionado);
        
        return String.format("Fin del juego, el número era %s y se adivinó en %s intentos.", numeroAleatorio, conteoIntentos);
    } catch (Exception e) {
        return "Se produjo un error: " + e;
    }
}



    /* 
     
        2.	Se requiere una función en java que simule las ventas de tres años para un almacén. Para cada año, deberá generar 
        un aleatorio para cada mes hasta completar los 12 meses. La función se llamará Simular_ventas, y debe retornar un String 
        al final que muestre las ventas de cada año, así:
        
            Año 1
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 1:  $##.###.###
            
            Año 2
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 2: $##.###.###
            
            Año 3
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###

            Total ventas Año 3: $##.###.###
            
            Investigue sobre la clase DecimalFormat para mostrar bien la salida. 
            import java.text.DecimalFormat;
            DecimalFormat form_pesos = new DecimalFormat("$#,###.00");

        
      
    */

    
    public static String generarReporteVentas() {
    final int LIMITE_VENTAS = 1_000_000;

    StringBuilder reporte = new StringBuilder();
    DecimalFormat formatoMoneda = new DecimalFormat("$#,###.00");

    for (int anio = 1; anio <= 3; anio++) {
        double totalAnual = 0;
        reporte.append(String.format("Año %d:\n", anio));

        for (int mes = 1; mes <= 12; mes++) {
            double ventasMensuales = Math.random() * LIMITE_VENTAS;
            totalAnual += ventasMensuales;
            reporte.append(String.format("Ventas del mes %d: %s\n", mes, formatoMoneda.format(ventasMensuales)));
        }

        reporte.append(String.format("Total de ventas para el año %d: %s\n\n", anio, formatoMoneda.format(totalAnual)));
    }

    return reporte.toString();
}



    /*  
     
        3.	En una fábrica se tiene el siguiente patrón de empaque: En una estiba(o pallet) caben 16  cajas y en cada caja, 
        caben 30 bombillas. Desarrolle una función que se llame: Calcular_empaque que: reciba como argumento la cantidad de 
        bombillas que se deben empacar y a partir de allí: calcule cuántas cajas necesita, cuántas estibas o pallets necesita. 
        Luego escriba lo siguiente: 

        Para ### bombillas, se necesitan ## cajas y ## pallets. Se quedan ### bombillas sin empacar. Se empacará así:

        Pallet 1 --> Caja1, Caja2……,Caja16
        Pallet2 -->  Caja17, Caja18…..Caja 32
        .
        Pallet n -- > Caja m, caja m+1…..
        
        La función retornará un texto, con la información anterior. Pruebe la función llamándola desde el programa principal: solicite al usuario el número de bombillas e invoque la función para imprimir en el main, los resultados.



    */


public static String calcularEmpaque(int totalBombillas) {
    try {
        StringBuilder reporte = new StringBuilder();
        final int CAJAS_POR_PALLET = 16;
        final int BOMBILLAS_POR_CAJA = 30;

        int cantidadCajas = totalBombillas / BOMBILLAS_POR_CAJA;
        int bombillasRestantes = totalBombillas % BOMBILLAS_POR_CAJA;
        int cantidadPallets = (int) Math.ceil((double) cantidadCajas / CAJAS_POR_PALLET);

        reporte.append(String.format("Para %d bombillas, se necesitan %d cajas y %d pallets. Quedan %d bombillas sin empacar.\n", 
                                      totalBombillas, cantidadCajas, cantidadPallets, bombillasRestantes));

        int palletActual = 1;
        int cajasEnPallet = 0;

        for (int i = 1; i <= cantidadCajas; i++) {
            if (cajasEnPallet == CAJAS_POR_PALLET) {
                reporte.append(String.format("\nPallet %d => ", palletActual));
                palletActual++;
                cajasEnPallet = 0;
            }
            reporte.append(String.format("Caja %d, ", i));
            cajasEnPallet++;
        }
        
        return reporte.toString();
    } catch (Exception e) {
        return "Ha ocurrido un error\n" + e;
    }
}

    

    /* 
    

        4.	En un juego, cada jugador tiene 3 intentos para sacar cartas de una baraja. Las cartas van numeradas entre 1 y 10. 
        Una función Jugar_21, deberá simular el juego para una cantidad de usuarios que enviará el usuario desde el main entre 1 y 6.

        Para cada uno de los jugadores, el programa le calculará 3 cartas al azar y al final imprimirá el juego para cada jugador basado en las siguientes reglas: 
        
        Si saca 21 exactos: juego perfecto
        Si saca más de 21: se pasó
        Si saca menos de 21: faltaron puntos

        La función deberá imprimir los puntos de cada jugador junto con la regla anterior, como muestra el ejemplo:

        Jugador X, puntos 21 -- > juego perfecto
        Jugador Y, puntos 26 -- > se pasó
        .
        .


    */

public static String juego_cartas(byte n_jugadores) {
    try {
        final byte MAX_JUGADORES = 6;
        final byte MIN_JUGADORES = 1;
        
        if (n_jugadores < MIN_JUGADORES || n_jugadores > MAX_JUGADORES) {
            return String.format("Tiene que haber entre %s y %s jugadores", MIN_JUGADORES, MAX_JUGADORES);
        }

        final byte MAX_CARTA = 10;
        final byte MIN_CARTA = 1;
        final byte NUM_CARTAS = 3;
        final byte PERFECTO = 21;

        byte carta, total;
        StringBuilder mensaje = new StringBuilder();

        for (int i = 1; i <= 3; i++) {
            mensaje.append(String.format("\n-----Intento %s-----", i));
            
            for (int j = 1; j <= n_jugadores; j++) {
                total = 0;
                mensaje.append(String.format("\nJugador %s => ", j));
                
                for (int k = 1; k <= NUM_CARTAS; k++) {
                    carta = (byte) (Math.random() * (MAX_CARTA) + MIN_CARTA);
                    total += carta;
                    mensaje.append(String.format("%s, ", carta));
                }
                
                mensaje.append(String.format("\nTotal => %s\t", total));
                
                if (total < PERFECTO) {
                    mensaje.append("faltaron puntos");
                } else if (total > PERFECTO) {
                    mensaje.append("se pasó");
                } else {
                    mensaje.append("juego perfecto");
                }
            }
        }
        
        return mensaje.toString();
    } catch (Exception e) {
        return "Ha ocurrido un error\n" + e;
    }
}


}
